steps:
- name: 'python'
  entrypoint: 'python'
  args: ['-m', 'pip', 'install', '--upgrade', 'pip']

# install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt","--user"]


# docker build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/bionic-tracer-421106/python/myapp:$SHORT_SHA', '.' ]

# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'us-central1-docker.pkg.dev/bionic-tracer-421106/python/myapp:$SHORT_SHA']


# Store images in Google Artifact Registry 
images:
- 'us-central1-docker.pkg.dev/bionic-tracer-421106/python/myapp:$SHORT_SHA'


options:
  logging: CLOUD_LOGGING_ONLY